export enum NotificationType {
    FRIEND_REQUEST = 'FRIEND_REQUEST',
    FRIEND_ACCEPTED = 'FRIEND_ACCEPTED',
    REJECTED = 'REJECTED',
    NEW_MESSAGE = 'NEW_MESSAGE',
    CHAT_INVITE = 'CHAT_INVITE',
    LOGIN_DETECTION = 'LOGIN_DETECTION',
    SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
    USER_JOINED = 'USER_JOINED',
}
